--
-- AUTHENTICATION/AUTHORIZATION
--
CREATE TABLE HCMS_USER(ID UUID default gen_random_uuid()::text PRIMARY KEY, LOGIN VARCHAR(1024) UNIQUE NOT NULL, FIRST_NAME VARCHAR(1024) UNIQUE NOT NULL, LAST_NAME VARCHAR(1024) UNIQUE NOT NULL, PASSWORD_HASH VARCHAR(2048) NOT NULL, ENABLED BOOLEAN);
CREATE TABLE HCMS_ROLE(ID VARCHAR(36) default gen_random_uuid()::text PRIMARY KEY, NAME VARCHAR(255) UNIQUE NOT NULL);
CREATE TABLE HCMS_USER_ROLE(USER_ID VARCHAR(36), ROLE_ID VARCHAR(36), PRIMARY KEY(USER_ID, ROLE_ID));
CREATE INDEX HCMS_USER_LUNAME ON OAUTH2_USER ((lower(LOGIN)));
CREATE INDEX HCMS_USER_UNAME ON OAUTH2_USER (LOGIN);
CREATE INDEX HCMS_ROLE_NAME ON HCMS_ROLE (NAME);
