/*
 * Copyright (c) 2024 - present - Yupiik SAS - https://www.yupiik.com
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.yupiik.hcms.service.model;

import io.yupiik.fusion.json.schema.validation.ValidationResult;
import io.yupiik.hcms.service.model.json.Model;
import io.yupiik.hcms.service.sql.SQLBiConsumer;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

// mainly acts as a normalized model and pre-computation of shared data between methods
public record Entity(
        String name,
        String table,
        Map<String, Model.GenerationType> createVirtualFields,
        Map<String, Model.GenerationType> updateVirtualFields,
        boolean autoGeneratedIds,
        List<String> identifiers,
        Set<String> allowedSortKeys,
        Set<String> allowedFilterKeys,
        Set<String> allowedWhereOperators,
        String revisionProperty,
        Model.JsonSchema schema,
        NameMapping mapping,
        Model.EntityImplicitFiltering implicitFiltering,
        Function<Object, ValidationResult> validator,
        String whereIds,
        SQLBiConsumer<ModelHandler.BindingContext, PreparedStatement> bindIdsNotNullable,
        SQLBiConsumer<ModelHandler.BindingContext, PreparedStatement> bindIdsNullable) {
    public record NameMapping(Map<String, String> jsonToDatabase, Map<String, String> databaseToJson) {}
}
