name: Github CI

on: [ push, pull_request ]

env:
  MAVEN_OPTS: -Dmaven.artifact.threads=256 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    name: Main Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        id: clone
        uses: actions/checkout@v4
      - name: Set up JDK 21
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Build
        run: mvn package -e
      - name: Remove Snapshots Before Caching
        run: find ~/.m2/repository -name '*SNAPSHOT' | xargs rm -Rf
  deploy-doc:
   if: github.ref == 'refs/heads/main'
   name: Documentation
   runs-on: ubuntu-20.04
   permissions:
     pages: write
     id-token: write
   environment:
     name: github-pages
   steps:
     - name: Clone
       id: clone
       uses: actions/checkout@v4
     - name: Set up JDK 21
       id: java21
       uses: actions/setup-java@v4
       with:
         distribution: 'zulu'
         java-version: '21'
         cache: 'maven'
     - name: Deploy-Documentation
       run: mvn package -s .github/settings.xml -Pgh-pages -e -DskipTests
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
     - uses: actions/upload-pages-artifact@v3.0.1
       with:
         path: target/__site
     - id: deployment
       uses: actions/deploy-pages@v4.0.4
     - name: Remove Snapshots Before Caching
       run: find ~/.m2/repository -name '*SNAPSHOT' | xargs rm -Rf
